# GitHub repository settings
# This file configures various repository settings

# Repository name and description
repository:
  name: SolidDocs
  description: A self-contained document collaboration and signing library for ASP.NET Core applications

# Default branch
default_branch:
  name: main

# Repository features
features:
  wiki: false
  issues: true
  projects: false
  discussions: false

# Repository settings
settings:
  # Set default language to English
  default_language: en
  
  # Enable GitHub Pages
  pages:
    source:
      branch: main
      path: /
  
  # Security settings
  security_and_analysis:
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: enabled
    dependency_graph:
      status: enabled
    dependabot_alerts:
      status: enabled
    dependabot_security_updates:
      status: enabled
    advanced_security:
      status: enabled

# Branch protection rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions: null 